# Generated by Django 5.1 on 2024-09-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authusermodel',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authusermodel',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='authusermodel',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
